name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3

      - name: Setup Node.js environment
        uses: actions/setup-node@3
        with:
          node-version: 16.17.0

      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
          
      - name: Install Dependencies
        run: npm install
     
      - name: Build
        run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.IIR_TOKEN }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./docs
